"""add_prompt_status_and_scope

Revision ID: 0e0a47c4ec9a
Revises: add_lead_updated_at
Create Date: 2025-12-13 19:59:03.910560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0a47c4ec9a'
down_revision: Union[str, None] = 'add_lead_updated_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('prompt_bundles', sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'))
    op.add_column('prompt_bundles', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('prompt_bundles', sa.Column('source_bundle_id', sa.Integer(), nullable=True))
    op.add_column('prompt_bundles', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.create_foreign_key(None, 'prompt_bundles', 'prompt_bundles', ['source_bundle_id'], ['id'])
    op.add_column('prompt_sections', sa.Column('scope', sa.String(length=50), nullable=False, server_default='custom'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tenant_sms_configs_tenant_id_key'), 'tenant_sms_configs', ['tenant_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('prompt_sections', 'scope')
    op.drop_constraint(None, 'prompt_bundles', type_='foreignkey')
    op.drop_column('prompt_bundles', 'updated_at')
    op.drop_column('prompt_bundles', 'source_bundle_id')
    op.drop_column('prompt_bundles', 'published_at')
    op.drop_column('prompt_bundles', 'status')
    # ### end Alembic commands ###

